### ISSUE TITLE
Consider increasing the time before data removal

### ISSUE THREAD

**Issue by RoneoOrg** [jsonconnect/jsonconnect#1]
Hello there,

Jsonconnect is a great service and [could be the successor of Jsonbox for FossURL](https://github.com/bauripalash/fossurl/pull/30), the open-source URL shortener

As of today though, the links shortened on FossURL will be valid for only 30 days before Jsonconnect removes the corresponding data

Could you please consider the possibility to increase this duration, or even better, remove this limitation?

Merci !

**Comment by AnthonyArutyunov** [comment]
Sorry for the late reply. I will remove this limitation for now, we will see how this works out.

**Comment by RoneoOrg** [comment]
Thank you @AnthonyArutyunov !

I will update the documentation of Fossurl to reflect this great update
