### ISSUE TITLE
Using Jsonconnect with Fossurl is now broken

### ISSUE THREAD

**Issue by RoneoOrg** [jsonconnect/jsonconnect#2]
Hi,

Jsonconnect used to work with [Fossurl](https://github.com/bauripalash/fossurl), but it's not the case anymore.

I set up a [dedicated Gitlab repository](https://framagit.org/roneo/app) to gather some information, but failed to fix it by myself.

Here is what I can tell:

- Fossurl works fine with Jsonbox, a [demo is available online](https://palashbauri.in/fossurl/)

- I [cloned the project](https://framagit.org/roneo/app/-/commits/master) and the test is successful until I move from Jsonbox to Jsconnect

This move is contained in three tiny commits:
  - the main is "[moving from jsonbox to jsonconnect](https://framagit.org/roneo/app/-/commit/6251de2c01a7cd54e631844457cf2111dee1bfa4)" 
  - I set up a basic CI in "[add .gitlab-ci.yml](https://framagit.org/roneo/app/-/commit/fad091762e5cd85465352c8fadca0dc7d99cf8a0)" to properly serve [the demo](https://roneo.frama.io/app/src/)
  - I finally tried [another Jsonconnect endpoint](https://framagit.org/roneo/app/-/commit/4de5b4fb39352986040f24ff7dd2693d7c8a1387). No success

The only hint I can spot is this error in the console:

```
Uncaught TypeError: res is undefined
    <anonymous> https://roneo.frama.io/app/src/head.js:21
```

I'm stuck in there. Any hint?

**Comment by AnthonyArutyunov** [comment]
Do not worry. This was on my side. After messing around a bit I found that I cannot remove the line that states how long data is stored entirely. To counter this I set the amount data can be stored to 99999 days, which is somewhere over 200 years.

If it is still not working, here is my head.js code:

```var endpoint = "http://jsonconnect.com/connect_a097bde63a1260191d3a";

function fetchJSON(a) {
    var f = new XMLHttpRequest;
    f.open("GET", a, false);
    f.send(null);
    return f.responseText
}

function isURL(a) {
    let url = a
    if (!a.startsWith("javascript:")) {
        return true;
    } else {
        return false;
    }
}
var hashh = window.location.hash.substr(1);
if (window.location.hash != "") {
    var res = JSON.parse(fetchJSON(endpoint + "/?q=s:" + hashh))[0];
    var data = res["l"];
    console.log(data);
    if (data != null) {
        if (isURL(data)) {
            window.location.href = data;
        }
    }
}
```

**Comment by RoneoOrg** [comment]
It works like a charm now, thanks a lot!

I updated the [Pull request for Fossurl](https://github.com/bauripalash/fossurl/pull/30) accordingly.

Thank you!
